version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew check
      - run: ./gradlew jacocoTestReport
      - run: ./gradlew jar
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
            - ~/work/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/libs
          destination: libs
      - store_test_results:
          path: build/test-results
